---
title: 'MTH 463 \n Homework #5'
author: "Duncan Gates"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  prettydoc::html_pretty:
    theme: leonids # Other options are cayman, tactile, architect, leonids, hpstr
    highlight: vignette
    math: katex #Instead of mathjax so it works offline
documentclass: book
classoption:
  - twocolumn
  - landscape
papersize: a5
linestretch: 1.5
fontsize: 12pt
links-as-notes: true
header-includes:
  - \usepackage{indentfirst}
---

```{r setup, include=FALSE}
# library(pagedown)
# setwd("/Users/dunk/Classes/MTH463/Homework 5")
# pagedown::chrome_print(input = "Homework-5.html",
#                       output = "Homework5.pdf")
```

## Problem 1

I check that f(x) is a probability density function by finding if the cumulative distribution function is 1 

$$
\begin{aligned}
1&=\int_{-\infty}^{\infty}f(x)dx \\
&=\int_{1}^{\infty}\frac{cdx}{x^4} \\
&=\Bigg[\frac{cx^{-3}}{-3}\Bigg]_{1}^{\infty} \\
&= \frac{c}{3} \\
c&= \boxed{3}
\end{aligned}
$$

To find $E[X]$ we use 

$$
\begin{aligned}
E[X]&=\int_{-\infty}^{\infty}xf(x)dx \\
&=\int_{1}^{\infty}\frac{3xdx}{x^4} \\
&=3\int_{1}^{\infty}\frac{dx}{x^3} \\
&=\Bigg[\frac{3x^{-2}}{-2}\Bigg]_{1}^{\infty} \\
&=\boxed{\frac{3}{2}}
\end{aligned}
$$

To find $Var[X]$ we use $Var[X] = E[X^2] - E[X]^2$

$$
\begin{aligned}
E[X^2]&=\int_{-\infty}^{\infty}x^2f(x)dx \\
&= \int_1^{\infty}\frac{3x^2dx}{x^4} \\
&=3\int_{1}^{\infty}\frac{dx}{x^2} \\
&=3\Bigg[\frac{3x^{-1}}{-1}\Bigg]_{1}^{\infty} \\
&=3 \\
Var[X] &= E[X^2] - E[X]^2 \\
&=3-\frac{3}{2}^2
&=\boxed{\frac{3}{4}}
\end{aligned}
$$


## Problem 2

$$
\begin{aligned}
E[e^z]&=\int_{-\infty}^{\infty}f_Z(x)dx \\
&= \frac{1}{2\pi}\int_{-\infty}^{\infty}e^xe^{\frac{-x^2}{2}}dx \\
&= \frac{1}{2\pi}\int_{-\infty}^{\infty}e^{x-\frac{-x^2}{2}}dx \\
&= e^\frac{1}{2}\frac{1}{2\pi}\Bigg[e^{-\frac{u^2}{2}} \Bigg]_{-\infty}^{\infty} && \text{Let } u = x - 1 \\
&= e^\frac{1}{2} \\
&= \boxed{\sqrt{e}}
\end{aligned}
$$


## Problem 3 

$$
\begin{aligned}
V(X+Y)&=E[(X+Y)^2]-(E[X+Y])^2 \\
&=E[X^2+2XY+Y^2]-(E[X]+E[Y])^2 \\
&=E[X^2]-(E[X])^2+E[Y^2]-2E[XY]+2E[X]E[Y] \\
&=E[X^2]-(E[X])^2-(E[Y])^2 \\
&\text{We know }E[X*Y]=E[X]*E[Y] \text{, so} \\
&=\boxed{Var(X)+Var(Y)}
\end{aligned}
$$



## Problem 4

$$
\begin{aligned}
f_{x_1+x_2+x_3}(a)&=\int_{-\infty}^{\infty}f_{x_1+x_2}(x)f_{x_3}(a-x) \\
&=\int_0^1xf_{x)3}(a-x)dx+\int_1^2(2-x)f_{x_3}(a-x)dx \\
&=  \begin{cases} 
      \int_0^axdx & \text{if } 0\leq a \le 1 \\
      \int_{a-1}^1xdx+\int_1^a(2-x)dx & \text{if } 1\leq a \le 2 \\
      \int_{a-1}^2(2-x)dx & \text{if } 2\leq a \le 3 \\
      0 & \text{otherwise}
   \end{cases} \\
&=  \boxed{\begin{cases} 
      \frac{a^2}{2} & \text{if } 0\leq a \le 1 \\
      -a^2+3a-\frac{3}{2} & \text{if } 1\leq a \le 2 \\
      \frac{a^2}{2}-3a+\frac{9}{2} & \text{if } 2\leq a \le 3 \\
      0 & \text{otherwise}
   \end{cases}}
\end{aligned}
$$


## Problem 5

Let S be the number of successes. S is therefore binomial with the parameters $n = 1210, p = \frac{1}{11}$.

Thus we have $E[S]=np=1210*\frac{1}{11}=110$,and $\sigma(S)=\sqrt{1210*\frac{1}{11}(1-\frac{1}{11})}=10$.

By the DeMoivre-Laplace limit theorem,

$$
\begin{aligned}
P(97.5 \le S \le 116.5)&=P(-12.5 \le S-np \le -6.5) \\
&=P(-1.25 \le \frac{S-np}{\sqrt{np(1-p)}} \le 0.65) \\
&=P(-1.25 \le Z \le 0.65) \\
&= \boxed{0.6366} \text{ according to R}
\end{aligned}
$$

## Problem 6

Let H be the number of heads, H is binomial and has parameters $n = 90,000$ and $p = \frac{1}{2}$.

Therefore $E[H]=90,000*\frac{1}{2}=45,000$ and $\sigma(H)=\sqrt{90,000*\frac{1}{2}(1-\frac{1}{2})}=150$.

Thus, by the DeMoivre-Laplace limit theorem,

$$
\begin{aligned}
P(45,031.5 \le H \le 45,169.5)&=P(31.5 \le H-np \le 169.5) \\
&=P(\frac{31.5}{150} \le \frac{H-np}{\sqrt{np(1-p)}} \le \frac{169.5}{150}) \\
&=P(0.21 \le Z \le 1.13) \\
&= \boxed{0.2876} \text{ according to R}
\end{aligned}
$$

## Problem 7

Just want to solve this one the normal way first, since it says estimate I also solve with DeMoivre-Laplace.

We have $n = 18,000$ and $p=\frac{1}{6}$, so $E[X]=3,000$ and $Var[X]=np(1-p)=18,000*\frac{1}{6}*\frac{5}{6}=2500$

By the Central Limit Theorem,

$$
\begin{aligned}
P(Z=\frac{X-E[X]}{\sqrt{Var[X]}} \ge 3,060) &=P(\frac{X-3,000}{50} \ge \frac{3,060-3,000}{50}) \\
&=P(Z \ge 1.2) \\
&=1-P(Z<1.2) \\
&\approx \boxed{0.1151} \text{ in R 1-pnorm(1.2, lower.tail = T)}
\end{aligned}
$$

This time estimating by the DeMoivre-Laplace limit theorem where S is binomial with the above parameters 

$$
\begin{aligned}
P(3,059.5 \le S < \infty)&=P(59.5 \le S-np< \infty) \\
&=P(\frac{59.5}{50} \le \frac{S-np}{\sqrt{np(1-p)}}< \frac{\infty}{50}) \\
&=P(0.21 \le Z < \infty) \\
&= \boxed{0.1170} \text{ which is pretty close to the CLT approximation}
\end{aligned}
$$








