---
title: "STAT 421 \n Assignment #5"
author: "Duncan Gates"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  prettydoc::html_pretty:
    theme: tactile # Other options are cayman, tactile, architect, leonids, hpstr
    highlight: vignette
    math: katex #Instead of mathjax so it works offline
documentclass: book
classoption:
  - twocolumn
  - landscape
papersize: a5
linestretch: 1.5
fontsize: 12pt
links-as-notes: true
header-includes:
  - \usepackage{indentfirst}
  - \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pagedown)
setwd("/Users/dunk/Classes/STAT421/Assignment 5")
pagedown::chrome_print(input = "Assignment-5.html",
                      output = "Assignment5.pdf")
```

## 3.148

We have the movement-generating function for $Y$ as 

$$
m(t)=\frac{pe^t}{1-qe^t} \text{, where } q = 1-p
$$
Differentiating we have, 

$$
\begin{aligned}
E(Y)&=\frac{\delta}{\delta t}m(t)\Bigg|_{t=0} \\
&=\frac{\delta}{\delta t}(\frac{pe^t}{1-qe^t}) \\
&=\frac{pe^t(1-qe^t)-pe^t(-qe^t)}{(1-qe^t)^2}\Bigg|_{t=0} \\
&=\frac{pe^t}{1-qe^t}+\frac{pqe^{2t}}{(1-qe^t)^2} \\
&=\frac{p}{1-q}+\frac{pq}{(1-q)^2} \\
&=\frac{p}{p}+\frac{p(1-p)}{p^2} && \text{as } 1-p=q, p = 1-q \\
&= 1+\frac{1-p}{p} \\
&=\frac{p+1-p}{p} \\
&= \boxed{\frac{1}{p}}
\end{aligned}
$$

for $E(Y^2)$ we have 

$$
\begin{aligned}
E(Y^2)&=\frac{\delta^2}{\delta t^2}m(t)\Bigg|_{t=0} \\
&=\frac{\delta}{\delta t}(\frac{\delta}{\delta t}\frac{pe^t}{1-qe^t}) \\
&=\frac{\delta}{\delta t}(\frac{pe^t(1-qe^t)-pe^t(-qe^t)}{(1-qe^t)^2})\Bigg|_{t=0} \\
&=\frac{pe^t}{1-qe^t}+\frac{3pqe^{2t}}{(1-qe^t)^2}+\frac{2pqe^{3t}}{(1-qe^t)^3}\Bigg|_{t=0} \\
&=\frac{p}{1-q}+\frac{3pq}{(1-q)^2}+\frac{2pq^2e^{3t}}{(1-q)^3} \\
&=\frac{p}{p}+\frac{3pq}{p^2}+\frac{2pq^2}{p^3} \\
&= 1+\frac{3q}{p}+\frac{2pq^2}{p^3} \\
&=\frac{p^2+3pq+2q^2}{p^2} \\
&= \frac{p^2+3p(1-p)+2(1-p)^2}{p^2} \\
&= \boxed{\frac{2-p}{p^2}}
\end{aligned}
$$

The variance is calculated as $V(Y) = E(Y^2)-E(Y)^2$ so we have 

$$
\begin{aligned}
V(Y)&=\frac{2-p}{p^2}-(\frac{1}{p})^2 \\
&=\frac{2-p-1}{p^2} \\
&= \boxed{\frac{1-p}{p^2}}
\end{aligned}
$$


## 3.154

**a.**

We have $m(t)=((\frac{1}{3})e^t+\frac{2}{3})^5$, so using the movement generating function of binomial random varialbe's the mean of a random variable is 

$$
\begin{aligned}
E(Y)&=\frac{\delta}{\delta t}m(t)\Bigg|_{t=0} \\
&=\frac{\delta}{\delta t}(\frac{1}{3}e^t+\frac{2}{3})^5 \\
&=5(\frac{1}{3}e^t+\frac{2}{3})^{5-1}*\frac{1}{3}e^t\Bigg|_{t=0} \\
&= \boxed{\frac{5}{3}}
\end{aligned}
$$

For a random variable squared, and subsequently the variance we have

$$
\begin{aligned}
E(Y^2)&=\frac{\delta^2}{\delta t^2}m(t)\Bigg|_{t=0} \\
&=\frac{5}{3}\frac{\delta}{\delta t}(\frac{1}{3}e^t+\frac{2}{3})^{5-1}) \Bigg|_{t=0} \\
&=\frac{20}{9}(\frac{1}{3}e^t+\frac{2}{3})^3e^{2t}+\frac{5}{3}(\frac{1}{3}e^t+\frac{2}{3})^4e^t\Bigg|_{t=0} \\
&= \frac{35}{9} \\
V(Y)&=E(Y^2)-E(Y)^2 \\
&=\frac{35}{9}-\frac{5}{3}^2\\
&=\boxed{\frac{10}{9}}
\end{aligned}
$$

**b.**

We have  $m(t)=\frac{pe^t}{(1-qe^t)}$ and the given mgf $m(t)=\frac{e^t}{2-e^t}$ which can be rewritten as $\frac{\frac{1}{2}e^t}{1-\frac{1}{2}e^t}$.

Once again for a random variable we have 

$$
\begin{aligned}
E(Y)&=\frac{\delta}{\delta t}m(t)\Bigg|_{t=0} \\
&=\frac{\delta}{\delta t} \frac{\frac{1}{2}e^t}{1-\frac{1}{2}e^t} \Bigg|_{t=0} \\
&= \frac{1}{2}\frac{e^t}{1-\frac{1}{2}e^t}+\frac{1}{4}\frac{(e^t)^2}{(1-\frac{1}{2}e^t)^2} \Bigg|_{t=0} \\
&= \boxed{2}
\end{aligned}
$$

For a random variable squared, and subsequently the variance we have

$$
\begin{aligned}
E(Y^2)&=\frac{\delta^2}{\delta t^2}m(t)\Bigg|_{t=0} \\
&=\frac{\delta^2}{\delta t^2}\frac{\frac{1}{2}e^t}{1-\frac{1}{2}e^t} \Bigg|_{t=0} \\
&=\frac{1}{2}(\frac{\frac{1}{2}e^t}{1-\frac{1}{2}e^t})+\frac{3}{4}(\frac{\frac{1}{2}e^t}{1-\frac{1}{2}e^t})^2+\frac{1}{4}(\frac{\frac{1}{2}e^t}{1-\frac{1}{2}e^t})^3 \Bigg|_{t=0} \\
V(Y)&=E(Y^2)-E(Y)^2 \\
&=6-(2)^2 \\
&= \boxed{2}
\end{aligned}
$$


**c.**

We are given the movement generating function $m(t)=e^{2(e^t-1)}$, thus the mean of a random variable is

$$
\begin{aligned}
E(Y)&=\frac{\delta}{\delta t}m(t)\Bigg|_{t=0} \\
&=\frac{\delta}{\delta t}(e^{2(e^t-1)})\Bigg|_{t=0} \\
&=2e^te^{2e^t-2}\Bigg|_{t=0} \\
&= \boxed{2}
\end{aligned}
$$

For a random variable squared, and subsequently the variance we have

$$
\begin{aligned}
E(Y^2)&=\frac{\delta^2}{\delta t^2}m(t)\Bigg|_{t=0} \\
&=\frac{\delta}{\delta t}(e^{2(e^t-1)})\Bigg|_{t=0} \\
&=2e^te^{2e^t-2}+4(e^t)^2e^{2e^t-2}\Bigg|_{t=0} \\
&= 6 \\
V(Y)&=E(Y^2)-E(Y)^2 \\
&=6-(2)^2 \\
&=\boxed{2}
\end{aligned}
$$

## 3.158

Given $W = aY+b$ the movement generating function $m_w(t)$ is defined as 

$$
\begin{aligned}
m_w(t)&=E(e^{tw}) \\
&=E(e^{t(aY+b)}) \\
&= E(e^{bt}e^{(at)Y}) \\
&= \boxed{e^{bt}m(at)}
\end{aligned}
$$

## 3.160

**a.**

$$
\begin{aligned}
E(Y*)&=E(n-Y) \\
&=n-E(Y) \\
&=n-np \\
&=n(1-p) \\
&= \boxed{nq}
\end{aligned}
$$

$$
\begin{aligned}
V(Y*)&=V(n - y) \\
&=V(y) \\
&=\boxed{npq}
\end{aligned}
$$

**b.**

The movement generating function of Y, given that it is binomial and has parameters p and n is given by
$$
\begin{aligned}
m_{Y^*}(t)&=E(e^{tY^*}) \\
&=E(e^{t(n-Y)}) \\
&=E(e^{nt}e^{(-t)Y}) \\
&=e^{nt}m(-t) \\
&= \boxed{(pe^t+q)^n}
\end{aligned}
$$

**c.**

Since we know $m_{Y^*}(t)= (pe^t+q)^n$, we can say that $Y^*$ has a binomial distribution

**d.**

Since Y is the number of successes in a sample size n, then $Y^*=(n - y)$ must represent the number of failures in sample size n.

**e.**

The answers to parts a,b, and c are obvious based on the answer in d because the classification of success and failure in the Bernoulli trial is arbitrary.
