---
title: "Homework 1"
author: "Duncan Gates"
date: "9/28/2020"
output: 
  prettydoc::html_pretty:
    theme: hpstr # Other options are cayman, tactile, architect, leonids, hpstr
    highlight: vignette
    math: katex
documentclass: book
classoption:
  - twocolumn
  - landscape
papersize: a5
linestretch: 1.5
fontsize: 12pt
links-as-notes: true
header-includes:
  - \usepackage{indentfirst}
  - \usepackage{ulem}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library(pagedown)
# setwd("/Users/dunk/MTH463")
# pagedown::chrome_print(input = "Homework-1.html",
#                       output = "Homework-1.pdf")
```

## Question 1

Prove: $\sum\limits_{k = 0}^n {n \choose k} (-1)^k = 0$

$\sum\limits_{k = 0}^n {n \choose k} (-1)^k = \sum\limits_{k = 0}^n {n \choose k} (-1)^k(1)^{n-k}$

$\{1-1\}^n=0^n=0$

## Question 2

Prove $\sum\limits_{k = 0}^n {n \choose k}^2 = {2n \choose n}$

Given ${n \choose k} = {n \choose n-k}$ 

apply this to $\sum\limits_{k = 0}^n {n \choose k}^2$ to get  $\sum\limits_{k = 0}^n {n \choose k}^2 = \sum\limits_{k = 0}^n {n \choose k}{n \choose {n -k}}$ by the multiplicative rule of counting

Which is ${n \choose 0}{n \choose n} + {n \choose 1}{n \choose n - 1}+...+{n \choose n}{n \choose 0}$ when summed over k going from 0 to n.

So we can conclude that $\sum\limits_{k = 0}^n {n \choose k}^2 = {2n \choose n}$

## Question 3

In the word REDRESSER there is one D, three E's, three R's, and two S's.

The distinct number of letter combinations is therefore:

$\frac{9!}{3!3!2!} = \frac{362,880}{(6)(6)(2)} = \boxed{5,040}$


## Question 4

We have 12 people in committees of 3, 4, and 5. Going first by committee size 3 we have

${12 \choose 3}{9 \choose 4}{5 \choose 5}$

$\frac{12!}{3!*9!}*\frac{9!}{4!*5!}\frac{5!}{5!*0!}$  using ${n \choose x} = \frac{n!}{x!(n-x)!}$

We can then cancel $\frac{12!}{3!*\sout{9!}}*\frac{\sout{9!}}{4!*\sout{5!}}\frac{\sout{5!}}{5!*0!}$

To get $\frac{12!}{3!*4!*5!}$

Which is $\boxed{27,720}$, so there are 27,720 possible divisions.

## Question 5

The number of positive solutions of the equation is $x_1+x_2+...+x_r = n$ is ${n-1 \choose k-1}$

Therefore the number of solutions of $x_1+x_2+x_3+x_4=49$ is ${49-1 \choose 4-1} = {48 \choose 3}$

$\frac{48!}{3!*(48-3)!} = \frac{48*47*46}{3*2*1}$

Which gives us $\boxed{17,296}$ possible integer solutions.



## Question 6

Given $x_1+x_2+x_3+x_4=49$,

Let $y_1 = x_1,\; y_2 = x_2 -1,\; y_3=x_3-2,\; y_4=x_4-3$

So $x_1=y_1,\;x_2=y_2+1,\;x_3=y_3+2,\;x_4=y_4+3$

Then $x_1+x_2+x_3+x_4=49$ becomes $y_1+y_2+y_3+y_4=49-(1+2+3)=43$

Where $y_i\geq0,\;1\leq i \leq4$

Thus we have $n = 43,\; r = 4$ which gives us $43-1 \choose 4-1$

Which is $\frac{43!}{3!(43-3)!} = \frac{42*41*40*\sout{39!}}{3*2*1*\sout{39!}}$

So there are $\boxed{11,480}$ possible integer solutions.

## Question 7

Let the total number of steps be $n = 12$, the steps to the right be $b_1 = 7$, and the steps up be $b_2 = 5$

Using the multinomial rule we know ${n \choose b_1,b_2} = \frac{n!}{b_1!b_2!}$

So we have $\frac{12!}{7!*5!} = \frac{12*11*10*9*8}{5*4*3*2*1} = 792$

There $\boxed{792}$ possible paths.

## Question 8

There are ${7 \choose 3}$ paths from A to C and ${5 \choose 2}$ paths from C to B.

Therefore, by the multiplicative rule of counting we have ${7 \choose 3}{5 \choose 2}$

Which is $\frac{7!}{3!(7-3)!}*\frac{5!}{2!(5-2)!} = 350$ 

So there are $\boxed{350}$ possible paths.

## Question 9

There are 4 aces and 52 cards, and each of the 4 players will get $52/4=13$ cards

Further there are $4!$ ways to distribute aces so that each person receives one and

The remaining 48 cards must be distributed so that each person receives 12 of them

So we have $\frac{48!}{12!*12!*12!*12!}$ ways to be distributed.

Together we have $\boxed{4!*\frac{48!}{12!^4}}$ which is a very large number.


